# Generated by Django 5.2 on 2025-08-13 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0003_rename_port_mikrotikdevice_api_port_and_more'),
        ('upgrade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mikrotikdevice',
            name='upgrade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='upgrade.upgrade'),
        ),
    ]
