# Generated by Django 5.2 on 2025-08-13 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0004_mikrotikdevice_upgrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mikrotikdevice',
            name='upgrade',
        ),
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('changelog', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='backup.mikrotikdevice')),
            ],
        ),
    ]
