# Generated by Django 5.2 on 2025-08-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0005_remove_mikrotikdevice_upgrade_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='mikrotikdevice',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
