# Generated by Django 5.2 on 2025-08-14 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0006_mikrotikdevice_version'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upgrade',
        ),
    ]
