# Generated by Django 5.2 on 2025-08-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upgrade',
        ),
    ]
